#:kivy 1.11.1

<CreateAccountWindow>:
    name: "create"

    namee: namee
    osis: osis
    password: passw

    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "Create an Account"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8}
                text: "Name: "
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8}
                size_hint: 0.4, 0.12
                id: namee
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13}
                text: "OSIS: "
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13}
                size_hint: 0.4, 0.12
                id: osis
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13*2}
                text: "Password: "
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13*2}
                size_hint: 0.4, 0.12
                id: passw
                multiline: False
                password: True
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.3,"y":0.25}
            size_hint: 0.4, 0.1
            font_size: (root.width**2 + root.height**2) / 17**4
            text: "Already have an Account? Log In"
            on_release:
                root.manager.transition.direction = "left"
                root.login()

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Submit"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_release:
                root.manager.transition.direction = "left"
                root.submit()


<LoginWindow>:
    name: "login"

    osis: osis
    password: password

    FloatLayout:

        Label:
            text:"OSIS: "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.9}
            size_hint: 0.35, 0.15

        TextInput:
            id: osis
            font_size: (root.width**2 + root.height**2) / 13**4
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.9}
            size_hint: 0.4, 0.15

        Label:
            text:"Password: "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.7}
            size_hint: 0.35, 0.15

        TextInput:
            id: password
            font_size: (root.width**2 + root.height**2) / 13**4
            multiline: False
            password: True
            pos_hint: {"x": 0.45, "top":0.7}
            size_hint: 0.4, 0.15

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.2
            font_size: (root.width**2 + root.height**2) / 13**4
            text: "Login"
            on_release:
                root.manager.transition.direction = "up"
                root.loginBtn()

        Button:
            pos_hint:{"x":0.3,"y":0.3}
            size_hint: 0.4, 0.1
            font_size: (root.width**2 + root.height**2) / 17**4
            text: "Don't have an Account? Create One"
            on_release:
                root.manager.transition.direction = "right"
                root.createBtn()


<MainWindow>:
    name: "main"
    Button:
        text: "Daily Survey"
        size_hint: 0.5, 0.1
        pos_hint: {"x":0, "top":1}
        font_size: (root.width**2 + root.height**2) / 14**4
        on_release:
            root.manager.transition.direction = "right"
            root.takeSurvey()

    Button:
        text: "Data on Your School"
        size_hint: 0.5, 0.1
        pos_hint: {"x":0.5, "top":1}
        font_size: (root.width**2 + root.height**2) / 14**4
        on_release:
            root.manager.transition.direction = "left"
            root.getData()
    
    Image:
        source: 'covid.jpg'

    Button:
        pos_hint:{"x":0.05,"y":0.25}
        size_hint: 0.25, 0.1
        font_size: (root.width**2 + root.height**2) / 14**4
        text: "Logout"
        on_release: root.logout()

    Button:
        text: "Access Your QR Code Here"
        size_hint: 1, 0.2
        pos_hint: {"y":0}
        font_size: (root.width**2 + root.height**2) / 14**4
        on_release:
            root.manager.transition.direction = "up"
            root.getCode()

<DailySurveyInfo>:
    name: "surveyInfo"

    Label:
        text: "Survey Notice"
        size_hint: 0.8, 0.2
        pos_hint: {"x":0.1, "top":1}
        font_size: (root.width**2 + root.height**2) / 12**4
                
    Label:
        text: "This questionnaire can be completed only once"
        size_hint: 0.8,0.15
        pos_hint: {"x": 0.1, "y": 0.6}
        font_size: (root.width**2 + root.height**2) / 14**4
    Label:
        text: "per day on the same device. Please review"
        size_hint: 0.8,0.15
        pos_hint: {"x": 0.1, "y": 0.5}
        font_size: (root.width**2 + root.height**2) / 14**4
    Label:
        text: "carefully your answers before submitting."
        size_hint: 0.8,0.15
        pos_hint: {"x": 0.1, "y": 0.4}
        font_size: (root.width**2 + root.height**2) / 14**4

    Button:
        text: "<Back"
        font_size: (root.width**2 + root.height**2) / 14**4
        size_hint: 0.5, 0.25
        pos_hint: {"x":0, "y": 0.02}
        on_release:
            root.manager.transition.direction = "right"
            root.back()
    Button:
        text: "Start Survey>"
        font_size: (root.width**2 + root.height**2) / 14**4
        size_hint: 0.5, 0.25
        pos_hint: {"x":0.5,"y":0.02}
        on_release:
            root.manager.transition.direction = "left"
            root.startSurvey()

<DailySurvey>:
    name: "survey"
    fever: fever
    
    FloatLayout:
        cols:1
        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "Daily Survey"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 12**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0.05, "top":0.8}
                text: "Did you have fever greater than 100.4 degrees in the past 24 hours?"
                font_size: 20
                text_size: self.size

            Spinner:
                id: fever
                pos_hint: {"x":0.65, "top":0.75}
                size_hint: 0.2, 0.06
                font_size: (root.width**2 + root.height**2) / 16**4
                text: "No"
                values: ('Yes', 'No') 

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0.05, "top":0.8-0.13}
                text: "Were you in contact with anyone who appeared sick in the past 24 hours?"
                font_size: 20
                text_size: self.size

            Spinner:
                pos_hint: {"x":0.65, "top":0.75-0.13}
                size_hint: 0.2, 0.06
                font_size: (root.width**2 + root.height**2) / 16**4
                text: "No"
                values: ('Yes', 'No')

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0.05, "top":0.8-0.13*2}
                text: "Have you been in contact with anyone who tested positive for COVID-19 in the past 24h? "
                font_size: 20
                text_size: self.size

            Spinner:
                pos_hint: {"x":0.65, "top":0.75-0.13*2}
                size_hint: 0.2, 0.06
                font_size: (root.width**2 + root.height**2) / 16**4
                text: "No"
                values: ('Yes', 'No')
            
            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0.05, "top":0.8-0.13*3.25}
                text: "Did anyone in your household have a fever greater than 100.4 degrees in the past 24 hours?"
                font_size: 20
                text_size: self.size

            Spinner:
                pos_hint: {"x":0.65, "top":0.75-0.13*3}
                size_hint: 0.2, 0.06
                font_size: (root.width**2 + root.height**2) / 16**4
                text: "No"
                values: ('Yes', 'No')

            Button:
                pos_hint:{"x":0.3,"y":0.05}
                size_hint: 0.4, 0.10
                text: "Next Page"
                font_size: (root.width**2 + root.height**2) / 14**4
                on_release: 
                    root.manager.transition.direction = "left"
                    root.contSurvey()

<DailySurveyTwo>:
    Label:
        text: "Daily Survey"
        size_hint: 0.8, 0.2
        pos_hint: {"x":0.1, "top":1}
        font_size: (root.width**2 + root.height**2) / 12**4
    Label:
        size_hint: 0.5,0.12
        pos_hint: {"x":0.15, "top":0.85}
        text: "Do you have any of the following symptoms? (Check all that apply)"
        font_size: 20
        text_size: self.size

    CheckBoxLayout:
        pos_hint: {"center_x":0.5, "center_y":0.35}

    Button:
        pos_hint: {"x":0.55,"y": 0.15}
        text: "Back"
        size_hint: 0.3,0.07
        font_size: (root.width**2 + root.height**2) / 16**4
        on_release:
            root.manager.transition.direction = "right"
            root.back()

    Button:
        pos_hint:{"x":0.55,"y":0.05}
        size_hint: 0.3, 0.07
        text: "Next Page"
        font_size: (root.width**2 + root.height**2) / 16**4
        on_release:
            root.manager.transition.direction = "left"
            root.contSurvey()

<DailySurveyThree>:
    Label:
        text: "Daily Survey"
        size_hint: 0.8, 0.2
        pos_hint: {"x":0.1, "top":1}
        font_size: (root.width**2 + root.height**2) / 12**4
    Label:
        size_hint: 0.5,0.12
        pos_hint: {"x":0.15, "top":0.80}
        text: "Does anyone in your household have any of the following symptoms? (Check all that apply)"
        font_size: 20
        text_size: self.size

    CheckBoxLayout:
        pos_hint: {"center_x":0.5, "center_y":0.35}

    Button:
        pos_hint: {"x":0.55,"y": 0.15}
        text: "Back"
        size_hint: 0.3,0.07
        font_size: (root.width**2 + root.height**2) / 16**4
        on_release:
            root.manager.transition.direction = "right"
            root.back()

    Button:
        pos_hint:{"x":0.55,"y":0.05}
        size_hint: 0.3, 0.07
        text: "Finish Survey"
        font_size: (root.width**2 + root.height**2) / 16**4
        on_release:
            root.manager.transition.direction = "left"
            root.submitSurvey()

<CustLabel@Label>: 
    color: .761, .190, .810, 1
    
<CheckBoxLayout>:
    size_hint: .65, .65
    pos_hint: {'center_x':0.50, 'center_y':0.35}
    # creating box layout 
    BoxLayout: 
        # assigning orentation 
        orientation: "vertical"
        spacing: 3
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Fever or chills"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Cough"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Shortness of breath"
                size_hint_x: .6
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .3
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Fatigue"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Muscle aches"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Headache"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Loss of taste"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Sore throat"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Runny nose"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Nausea or vomiting"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
        
        BoxLayout: 
            orientation: "horizontal"
            size_hint_x: .40
            # label creation 
            CustLabel: 
                text: "Diarrhea"
                size_hint_x: .60
                font_size:20
            CheckBox: 
                color:.294, .761, .623
                size_hint_x: .30
            
<HealthyWindow>:
    name: "healthy"
    Label:
        text: 'Status: Healthy'
        pos_hint: {"center_x":0.5, "top":0.9}
        size_hint: 0.4, 0.1
        font_size: (root.width**2 + root.height**2) / 10**4

    Image:
        source: "check-qr.png"

    Button:
        pos_hint:{"x":0.1,"y":0.1}
        size_hint: 0.25, 0.1
        font_size: (root.width**2 + root.height**2) / 14**4
        text: "Back"
        on_release: app.goToMain()

<WarningWindow>:
    Label:
        text: 'Status: At Risk For COVID'
        pos_hint: {"center_x":0.5, "top":0.9}
        size_hint: 0.4, 0.1
        font_size: (root.width**2 + root.height**2) / 12**4

    Label:
        text: 'Based on your answers, you may be at risk of having COVID-19. Please do not come to school, contact your healthcare provider and get tested'
        text_size: root.width*.8, None
        pos_hint: {"center_x":0.5, "top":0.6}
        size_hint: 0.5, None
        font_size: (root.width**2 + root.height**2) / 14**4
            
    Button:
        pos_hint:{"x":0.1,"y":0.1}
        size_hint: 0.25, 0.1
        font_size: (root.width**2 + root.height**2) / 14**4
        text: "Back"
        on_release: app.goToMain()
    
<SchoolData>:
    Label:
        text: 'School Data'
        pos_hint: {"center_x":0.5, "top":0.9}
        size_hint: 0.4, 0.1
        font_size: (root.width**2 + root.height**2) / 10**4

    Image:
        source: 'pie-chart.png'

    Button:
        pos_hint:{"x":0.1,"y":0.1}
        size_hint: 0.25, 0.1
        font_size: (root.width**2 + root.height**2) / 14**4
        text: "Back"
        on_release: app.goToMain()



